name: Build SMV-Extracter Cross-Platform

on:
  push:
    branches: [ main, dev-build ]  # Add dev-build branch
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, dev-build ]  # Add dev-build branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    timeout-minutes: 60  # Maximum 1 hour per job
    strategy:
      matrix:
        os: [windows-latest]  # Focus on Windows only for now
        include:
          - os: windows-latest
            platform: windows
            extension: .exe
            installer: .bat
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Verify required files
      run: |
        echo "Checking required files..."
        ls -la
        if [ -f "requirements-minimal.txt" ]; then
          echo "requirements-minimal.txt found"
        else
          echo "requirements-minimal.txt missing"
          exit 1
        fi
        if [ -f "build_ci.py" ]; then
          echo "build_ci.py found"
        else
          echo "build_ci.py missing"
          exit 1
        fi
        if [ -f "main.py" ]; then
          echo "main.py found"
        else
          echo "main.py missing"
          exit 1
        fi
      shell: bash
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use 3.12 for better compatibility with latest packages
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-minimal.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Debug Python environment
      run: |
        python --version
        python -c "import sys; print('Python executable:', sys.executable)"
        python -c "import platform; print('Platform:', platform.platform())"
        pip --version
    
    - name: Install system dependencies (Windows)
      run: |
        # Use chocolatey to install ffmpeg (simpler and more reliable)
        choco install ffmpeg -y
      timeout-minutes: 5
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install nuitka
        # Install dependencies separately to handle failures better
        pip install -r requirements-minimal.txt
      timeout-minutes: 10  # Add timeout to prevent hanging
    
    - name: Verify dependencies
      run: |
        python -c "import customtkinter; print('CustomTkinter:', customtkinter.__version__)"
        python -c "import yt_dlp; print('yt-dlp:', yt_dlp.version.__version__)"
        python -c "import moviepy; print('MoviePy:', moviepy.__version__)"
        python -c "import numpy; print('NumPy:', numpy.__version__)"
        python -c "import PIL; print('Pillow:', PIL.__version__)"
        python -c "import nuitka; print('Nuitka installed successfully')"
    
    - name: Build with Nuitka
      run: python build_ci.py
      timeout-minutes: 45  # Add timeout for build process
    
    - name: Create installer script
      run: echo "Installer created by build_ci.py"
    
    - name: Package artifacts (Windows)
      run: |
        cd dist
        7z a -tzip SMV-Extracter-Windows-x64.zip main.dist install.bat
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SMV-Extracter-${{ matrix.platform }}-x64
        path: |
          dist/SMV-Extracter-*-x64.*
        retention-days: 30
    
    - name: Get file sizes
      run: |
        echo "Build Results:"
        dir dist\SMV-Extracter-Windows-x64.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*
        body: |
          ## SMV-Extracter Cross-Platform Release
          
          **Downloads:**
          - 🪟 **Windows**: `SMV-Extracter-Windows-x64.zip`
          - 🐧 **Linux**: `SMV-Extracter-Linux-x64.tar.gz`
          
          **Installation:**
          1. Download the appropriate file for your platform
          2. Extract the archive
          3. Run the installer script (`install.bat` or `install.sh`)
          
          **Features:**
          - YouTube video downloader
          - Frame extraction tools
          - Modern GUI interface
          - Cross-platform support
          
          **System Requirements:**
          - Windows 10+ or Ubuntu 18.04+
          - No Python installation required
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
