name: Build SMV-Extracter

on:
  push:
    branches: [ main, dev-build ]  
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, dev-build ]  
  workflow_dispatch:  

jobs:
  build:
    timeout-minutes: 60  
    strategy:
      matrix:
        os: [windows-latest]  
        include:
          - os: windows-latest
            platform: windows
            extension: .exe
            installer: .bat
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"  
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/uv
          ~\AppData\Local\uv\Cache
        key: ${{ runner.os }}-uv-${{ hashFiles('requirements-minimal.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    
    - name: Debug Python environment
      run: |
        python --version
        python -c "import sys; print('Python executable:', sys.executable)"
        python -c "import platform; print('Platform:', platform.platform())"
        pip --version
    
    - name: Install system dependencies (Windows)
      run: |
        
        choco install ffmpeg -y
      timeout-minutes: 5
    
    - name: Install Python dependencies
      run: |
        
        Write-Host "Installing uv..."
        python -m pip install uv
        
        Write-Host "Creating virtual environment..."
        uv venv
        
        Write-Host "Installing dependencies from requirements-minimal.txt..."
        if (Test-Path ".venv\Scripts\Activate.ps1") {
          .\.venv\Scripts\Activate.ps1
          uv pip install -r requirements-minimal.txt
          Write-Host "Dependencies installed in virtual environment"
        } else {
          Write-Host "Virtual environment activation failed"
          exit 1
        }
      timeout-minutes: 10  
    
    - name: Verify dependencies
      run: |
        
        if (Test-Path ".venv\Scripts\Activate.ps1") {
          .\.venv\Scripts\Activate.ps1
          python -c "import customtkinter; print('CustomTkinter:', customtkinter.__version__)"
          python -c "import yt_dlp; print('yt-dlp:', yt_dlp.version.__version__)"
          python -c "import moviepy; print('MoviePy:', moviepy.__version__)"
          python -c "import numpy; print('NumPy:', numpy.__version__)"
          python -c "import PIL; print('Pillow:', PIL.__version__)"
          python -c "import sv_ttk; print('sv_ttk: imported successfully')"
          Write-Host "All dependencies verified in virtual environment"
        } else {
          Write-Host "Virtual environment not found"
          exit 1
        }
    
    - name: Build with PyInstaller
      run: |
        
        if (Test-Path ".venv\Scripts\Activate.ps1") {
          .\.venv\Scripts\Activate.ps1
          python build_pyinstaller.py
        } else {
          Write-Host "Virtual environment not found"
          exit 1
        }
      timeout-minutes: 15  
    
    - name: Verify PyInstaller output
      run: |
        echo "Checking PyInstaller build output:"
        if (Test-Path "dist\SMV-Extracter-windows-x64.exe") {
          Write-Host "✓ Single executable found"
          $exeSize = (Get-Item "dist\SMV-Extracter-windows-x64.exe").Length / 1MB
          Write-Host "Executable size: $([math]::Round($exeSize, 2)) MB"
        } else {
          Write-Host "✗ Executable not found - PyInstaller build may have failed"
          Write-Host "Contents of dist directory:"
          if (Test-Path "dist") { dir dist -Recurse } else { Write-Host "dist directory not found" }
          exit 1
        }
    
    - name: Verify build artifacts
      run: |
        echo "Build Results:"
        echo "Directory listing of dist:"
        dir dist
        if (Test-Path "dist\SMV-Extracter-windows-x64.exe") {
          echo "✓ Single executable found"
          $exeSize = (Get-Item "dist\SMV-Extracter-windows-x64.exe").Length / 1MB
          Write-Host "Single executable size: $([math]::Round($exeSize, 2)) MB"
        } else {
          Write-Host "✗ Single executable not found"
          exit 1
        }
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SMV-Extracter-${{ matrix.platform }}-x64
        path: |
          dist/SMV-Extracter-windows-x64.exe
        retention-days: 30
    
    - name: Get file sizes
      run: |
        echo "Build Results:"
        if (Test-Path "dist\SMV-Extracter-windows-x64.exe") {
          $exeSize = (Get-Item "dist\SMV-Extracter-windows-x64.exe").Length / 1MB
          Write-Host "Final executable: SMV-Extracter-windows-x64.exe ($([math]::Round($exeSize, 2)) MB)"
        }

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*
        body: |
          ## SMV-Extracter Release
          
          **Single Executable Application**
          - Download `SMV-Extracter-windows-x64.exe`
          - No installation required - just run the executable
          - All dependencies included in the single file
          
          **Usage:**
          1. Download the executable
          2. Run directly - no installation needed
          3. First run may be slower due to extraction

        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
